development:
  adapter: postgresql
  database: mt_view_dev
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: mt_view_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: mt_view_prod
  pool: 5
  timeout: 5000